CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mail VARCHAR(255),
    password VARCHAR(255),
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    phone VARCHAR(255),
    birthday DATE,
    address VARCHAR(255),
    creation_date TIMESTAMPTZ,
    deletion_date TIMESTAMPTZ,
    modified_by BIGINT,
    modification_date TIMESTAMPTZ
);

CREATE UNIQUE INDEX uk_clients_mail_lower ON clients (LOWER(mail));

CREATE TABLE admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT REFERENCES roles(id),
    mail VARCHAR(255),
    password VARCHAR(255),
    employee_code VARCHAR(255),
    creation_date TIMESTAMPTZ,
    deletion_date TIMESTAMPTZ,
    modified_by BIGINT,
    modification_date TIMESTAMPTZ
);

CREATE TABLE agencies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country VARCHAR(255),
    location_code VARCHAR(255),
    name VARCHAR(255),
    creation_date TIMESTAMPTZ,
    deletion_date TIMESTAMPTZ,
    modified_by BIGINT,
    modification_date TIMESTAMPTZ
);

CREATE TABLE vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_price_per_day NUMERIC(12, 2),
    base_price_per_hour NUMERIC(12, 2),
    code_acriss VARCHAR(255),
    code_vin VARCHAR(255),
    license_plate VARCHAR(255),
    creation_date TIMESTAMPTZ,
    deletion_date TIMESTAMPTZ,
    modified_by BIGINT,
    modification_date TIMESTAMPTZ
);

CREATE TABLE agencies_vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_agency BIGINT REFERENCES agencies(id),
    id_vehicle BIGINT REFERENCES vehicles(id),
    start_date TIMESTAMPTZ,
    end_date TIMESTAMPTZ
);

CREATE TABLE rentals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_vehicle BIGINT REFERENCES vehicles(id),
    id_client BIGINT REFERENCES clients(id),
    id_agency BIGINT REFERENCES agencies(id),
    id_agency_start BIGINT REFERENCES agencies(id),
    id_agency_end BIGINT REFERENCES agencies(id),
    start_date TIMESTAMPTZ,
    end_date TIMESTAMPTZ,
    price NUMERIC(12, 2),
    deal NUMERIC(12, 2),
    status VARCHAR(255),
    deletion_date TIMESTAMPTZ,
    creation_date TIMESTAMPTZ,
    modified_by BIGINT,
    modification_date TIMESTAMPTZ
);

CREATE TABLE bills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_client BIGINT REFERENCES clients(id),
    id_rental BIGINT REFERENCES rentals(id),
    price NUMERIC(12, 2),
    status VARCHAR(255)
);

CREATE TABLE conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_client BIGINT REFERENCES clients(id),
    id_admin BIGINT REFERENCES admins(id),
    status VARCHAR(255),
    start_date TIMESTAMPTZ,
    end_date TIMESTAMPTZ
);

CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_conversation BIGINT REFERENCES conversations(id),
    id_sender BIGINT,
    status_sender VARCHAR(255),
    content TEXT,
    status VARCHAR(255),
    creation_date TIMESTAMPTZ,
    modification_date TIMESTAMPTZ
);

CREATE INDEX idx_admins_role_id ON admins(role_id);
CREATE INDEX idx_agencies_vehicles_agency ON agencies_vehicles(id_agency);
CREATE INDEX idx_agencies_vehicles_vehicle ON agencies_vehicles(id_vehicle);
CREATE INDEX idx_rentals_client ON rentals(id_client);
CREATE INDEX idx_rentals_vehicle ON rentals(id_vehicle);
CREATE INDEX idx_bills_client ON bills(id_client);
CREATE INDEX idx_bills_rental ON bills(id_rental);
CREATE INDEX idx_conversations_client ON conversations(id_client);
CREATE INDEX idx_conversations_admin ON conversations(id_admin);
CREATE INDEX idx_messages_conversation ON messages(id_conversation);
